# Permalinks
permalink:           pretty

# Setup
title:               Lauren Howard
tagline:             Metis Data Science Blog
url:                 http://laurenlagilson.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lauren Howard
  url:
  email:             laurenlhoward14@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/laurenlagilson

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
